Algoritmo "combinacao"
// Disciplina  : Algoritmo, Curso em Vídeo
// Professor   : Gustavo Guanabara 
// Descrição   : Algoritmo simples com a estrutura de repetição Para
// Autor(a)    : Erlon Mendes
// Data atual  : 20/04/2022
Var
// Seção de Declarações das variáveis 
   i, j: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para i <- 1 ate 3 faca
      para j <- 1 ate 3 faca
         escreval(i,j)
      fimpara
   fimpara
Fimalgoritmo