algoritmo "contador"
// Função : Algoritmo simples para a estrutura de repetição Enquanto
// Autor : Erlon Mendes
// Data : 18/04/2022
// Seção de Declarações 
var
   n, nf, step: inteiro
inicio
// Seção de Comandos
   escreva("Quer contar até quanto, mané? ")
   leia(nf)
   escreva("Qual o passo? ")
   leia(step)
   n <- 0
   enquanto (n <= nf) faca
      escreval("n = ", n)
      n <- n + step
   fimenquanto
fimalgoritmo
