Algoritmo "contador"
// Disciplina  : Algoritmo, Curso em Vídeo
// Professor   : Gustavo Guanabara 
// Descrição   : Algoritmo simples com a estrutura de repetição Para
// Autor(a)    : Erlon Mendes
// Data atual  : 20/04/2022
Var
// Seção de Declarações das variáveis 
   n: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   para n <- 1 ate 10 passo 1 faca
        escreval(n)
   fimpara
Fimalgoritmo